# Generated by Django 4.0.6 on 2022-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.CharField(max_length=300)),
                ('returns', models.CharField(max_length=300)),
                ('support', models.CharField(max_length=300)),
            ],
        ),
    ]
