# Generated by Django 4.0.6 on 2022-07-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bob', models.CharField(blank=True, max_length=200)),
                ('bnb', models.CharField(blank=True, max_length=200)),
                ('pnd', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(upload_to='products/%Y/%m/%d'),
        ),
    ]
