# Generated by Django 4.0.6 on 2022-07-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_number',
            old_name='pnd',
            new_name='bdb',
        ),
        migrations.AddField(
            model_name='account_number',
            name='pnb',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
