# Generated by Django 4.0.6 on 2022-07-16 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_pnd_account_number_bdb_account_number_pnb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='screenshot',
        ),
    ]
